/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.109
 * Generated at: 2022-01-21 07:47:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import oracle.jdbc.driver.OracleDriver;

public final class edit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table align=\"center\" width=\"1130\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"6\"><img src=\"imgs/img01.png\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><img src=\"imgs/img02.png\"></td>\r\n");
      out.write("\t\t\t<td align=\"center\" width=\"184\" background=\"imgs/img03.png\"><a href=\"index.jsp\">[HOME]</a></td>\r\n");
      out.write("\t\t\t<td align=\"center\" width=\"184\" background=\"imgs/img03.png\"><a href=\"intro.jsp\">[INTRO]</a></td>\r\n");
      out.write("\t\t\t<td align=\"center\" width=\"184\" background=\"imgs/img03.png\"><a href=\"list.jsp\">[B B S]</a></td>\r\n");
      out.write("\t\t\t<td align=\"center\" width=\"184\" background=\"imgs/img03.png\"><a href=\"guest.jsp\">[GUEST]</a></td>\r\n");
      out.write("\t\t\t<td><img src=\"imgs/img02.png\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\t\t\t\r\n");
      out.write("\t\t\t<td colspan=\"6\">\t\t\t\r\n");
      out.write("\t\t\t\t<!-- content start -->\r\n");
      out.write("\t\t\t\t<h1>수정페이지</h1>\r\n");
      out.write("\t\t\t\t");

					String num=request.getParameter("num");
					String sql="select num,sub,nalja,content from bbs01 where num="+num;
					String nalja=null;
					String sub=null;
					String content=null;
					String url="jdbc:oracle:thin:scott/tiger@localhost:1521:xe";
					Connection conn=null;
					Statement stmt=null;
					ResultSet rs=null;
					
					try{
						DriverManager.registerDriver(new OracleDriver());
						conn=DriverManager.getConnection(url);
						stmt=conn.createStatement();
						rs=stmt.executeQuery(sql);
						
						if(rs.next()){
							num=rs.getString(1);
							sub=rs.getString(2);
							nalja=rs.getString(3);
							content=rs.getString(4);
						}
					}catch(SQLException ex){
						
					}finally{
						if(rs!=null)rs.close();
						if(stmt!=null)stmt.close();
						if(conn!=null)conn.close();
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<form action=\"update.jsp\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"100\">No.</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"num\" value=\"");
      out.print(num);
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"100\">날짜</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"nalja\" value=\"");
      out.print(nalja);
      out.write("\" disabled=\"disabled\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>제목</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" name=\"sub\" value=\"");
      out.print(sub);
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"4\"><textarea name=\"content\">");
      out.print(content);
      out.write("</textarea></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"수 정\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"reset\" value=\"취 소\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<!-- content end -->\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"6\"><img src=\"imgs/img08.png\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
